### ISSUE TITLE
A distraction for Akama Quest bugg. [Fallen]

### ISSUE THREAD

**Issue by Namulex** [HeroesWoW/BugReports#58]
# OpenWoW/WoWHead Link
https://www.wowhead.com/quest=13429/a-distraction-for-akama

## Expected Behavior
According to Wowhead and videos from YouTube, Akama should be there and a event or play out should be going on which after that it would be marked finished.

## Current Behavior
Option is not available to talk to  Xi'ri to start the event, and or NPC's are not there.

## Possible Solution
Possible solution would be a insta completed quest as in you take it and its marked as completed.

## Context (Environment)
It would be nice if it was fixed, as a achievement hunter and title hunter it's pretty nice if these things work not only that but it keeps you also busy to keep playing the game.

##  Screenshots

**Comment by Fenukshwow** [comment]
Unfortunately it most likely won't be possible at this point in time due to the amount of bugged quests Fallen has. There isn't really a list of every bugged quest due to not everything that is bugged generally gets reported.

That being said, it may be possible when Both Realms gets a core update in future (https://forum.heroes-wow.com/threads...re-Update-info!) which will fix way more things overall than what is currently working on Fallen.

Cheddar - https://forum.heroes-wow.com/threads/5176-Loremaster-Achievement?p=18764&viewfull=1#post18764
