### ISSUE TITLE
 The Challenge quest [Fallen]

### ISSUE THREAD

**Issue by Namulex** [HeroesWoW/BugReports#59]
## OpenWoW/WoWHead Link
https://www.wowhead.com/quest=9015/the-challenge

## Expected Behavior
The quest called  [The Challenge] where you get your item called  [Banner of Provocation] in order to summon the boss in the middle of the room, in the dungeon called  Blackrock Depths. Here is the boss(s) you need to kill in order to complete the quest.

## Current Behavior
The current problem is no matter where you put the Banner, the boss simply doesn't spawn.

## Possible Solution
Possible solution would be to put the boss in there in the side, simple and easy. 
Or either sell the xmog (talking about the recollered heirlooms Dungeon set 2 ) at a vendor in xmog mall.
## Context (Environment)
It would be nice if it works to complete the quest for achievement but also because its fun in my opinion to do older quest.

##  Screenshots

**Comment by Fenukshwow** [comment]
Unfortunately it most likely won't be possible at this point in time due to the amount of bugged quests Fallen has. There isn't really a list of every bugged quest due to not everything that is bugged generally gets reported.

That being said, it may be possible when Both Realms gets a core update in future (https://forum.heroes-wow.com/threads...re-Update-info!) which will fix way more things overall than what is currently working on Fallen.

Cheddar - https://forum.heroes-wow.com/threads/5176-Loremaster-Achievement?p=18764&viewfull=1#post18764
