### ISSUE TITLE
Bug quest saving the princess stillpine

### ISSUE THREAD

**Issue by jumava** [HeroesWoW/BugReports#61]
Server: Fallen Heroes

when you open the princess cage, she left but the quest doesn't progress. you can't finish the quest.

https://www.wowhead.com/quest=9667/saving-princess-stillpine

when you open the princess cage, she slould thank you

## Current Behavior
she left the cage, and says go to the west, then she disappear

video:
https://youtu.be/YdkdTDK9-cs

**Comment by Fenukshwow** [comment]
Unfortunately it most likely won't be possible at this point in time due to the amount of bugged quests Fallen has. There isn't really a list of every bugged quest due to not everything that is bugged generally gets reported.

That being said, it may be possible when Both Realms gets a core update in future (https://forum.heroes-wow.com/threads...re-Update-info!) which will fix way more things overall than what is currently working on Fallen.

Cheddar - https://forum.heroes-wow.com/threads/5176-Loremaster-Achievement?p=18764&viewfull=1#post18764
