### ISSUE TITLE
[Unlimited] To low difference in stats with compare T5.5 and T6 Caster Staff

### ISSUE THREAD

**Issue by darhanger** [HeroesWoW/BugReports#97]
## Expected Behavior
I was hoping that the difference in spell power between t5.5 and t6 will be at least 5+K spell power like at t5 and t5,5. But in fact, there is not even 2 thousand

## Current Behavior
Difference in spell power between t5.5 and t6 only 1922 spell power.

## Possible Solution
Make correct scale like at t5 and t5.5 caster weapon. Because if you look and compare already t6 and t7 then we will see a giant difference at least 15+ k spell power

##  Screenshots
![asd4124](https://user-images.githubusercontent.com/22445395/48144924-6a4c9b80-e2ba-11e8-963c-79ac3a437a88.png)

**Comment by lordvolom1** [comment]
Wow! Big increase!

**Comment by Fenukshwow** [comment]
I do agree the difference is small but it is because T5.5 did not exist before the revamp. However, this is not a bug but you suggest a bigger increase hence this 'bug' issue will be closed. Furthermore - none is adapting the gear at this very moment because the class balance is upcoming in the near future. The class balance doesn't only include spells but also the scaling between tiers and donor items.
